### PR TITLE
fix(AccountModal): change value to Number in setAmount

### LINKED ISSUE #82: Bug: Account values are being concatenated together as strings rather than being added together as numbers
**Date Seen**
6/14/22

**Versions**
Android emulator
iOS 
Chrome
develop branch

**Bug Description**
The account amounts appear to be being concatenated together as a string rather than being added together as numbers.

accountbug

**Steps to Reproduce**
1. Start the app
2. Login
3. Click on the AccountsDropDown chevron
4. Click on the plus sign below "Income"
5. Add an account with an amount value and label, then click "Add Account"
6. Click on the plus sign again to add another account
7. Add another account with an amount value and label, then click "Add Account"
8. Observe that the values of the account appear side by side for the "Balance/Extra Money" values, rather than being added together as numbers

**Actual Behavior**
The account values for multiple new accounts appear to be being concatenated as strings.

**Expected Behavior**
The account values should be added together as Numbers.

**Troubleshooting/Testing Steps Attempted**
None yet

**Workaround**
none yet

### PR DESCRIPTION
**Pull request by srosenberg74**
**Changes**
* changed setAmount(newText) to setAmount(Number(newText)) in `AccountModal.tsx` to convert the value back to a number before the amount is added to the Redux state.

**Purpose**
* Convert the value to a number before it is added to the state so that it will be properly added as a number value rather than concatenated as a string.

**Approach**
* Converted the value to a number instead of a string.

**Learning**
No new learning for this one, just needed to do a type conversion, which we have become much more familiar with in the last week or two with TypseScript and Redux.

Closes #82

### CODE REVIEW

**Review by Tesfa-Worku — APPROVED** [review]
@srosenberg74 good job, the concatenation bug is resolved.

**Review by Tesfa-Worku — CHANGES_REQUESTED** [review]
there is a merge conflict.

**Comment by srosenberg74** [comment]
Hi @Tesfa-Worku!  The merge conflict should be resolved now.  Thank you!

**Review by Tesfa-Worku — APPROVED** [review]
@srosenberg74 thank you for resolving the merge conflicts.

**Pull request merged**
